### ISSUE TITLE
Add MacOS installation instructions

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#95] opened 2024-04-04 07:12 UTC
- Create a 'setup-macos' script at root of repo
- Add a 'MacOS' sub-section to the docs/docs/get-started/setting-up-la-vague installation guide

**Comment by willschneider15** [comment] 2024-04-05 07:17
https://github.com/lavague-ai/LaVague/pull/104

**Comment by 1of13** [comment] 2024-04-16 17:54
Thank you for adding a MacOS script. 

The url to chromedrive and chome in the script is outdated. See the error below. Also, after manually downloading the files, my computer refuses to launch them--even after "chmod +x". Any suggestions of how to fix that?

<img width="626" alt="SCR-20240416-jwvo" src="https://github.com/lavague-ai/LaVague/assets/31781349/b7161780-8345-4426-8285-b49eac8d4717">

**Comment by willschneider15** [comment] 2024-04-16 19:09
Try copying down just the bash script and running that. Since it was designed to do everything including clone down the repo.

Also take screenshots of your terminal including the commands you ran if you do have issues.

**Comment by 1of13** [comment] 2024-04-16 19:25
Thanks for the reply. Here is the command I ran and the results. Like I mentioned before, there are a bunch of errors.


(base) collective@collective LaVague % sudo bash setup-macos.sh              
Password:
https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.105/mac-arm64/chromedriver-mac-arm64.zip
https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.105/mac-arm64/chrome-mac-arm64.zip
setup-macos.sh: line 51: wget: command not found
unzip:  cannot find or open chromedriver-mac-arm64.zip, chromedriver-mac-arm64.zip.zip or chromedriver-mac-arm64.zip.ZIP.
mv: rename chromedriver-mac-arm64/ to /Users/collective/chromedriver-mac-arm64/: No such file or directory
mv: rename /Users/collective/chromedriver-mac-arm64 to /Users/collective/chromedriver-testing/chromedriver-mac-arm64: No such file or directory
rm: chromedriver-mac-arm64.zip: No such file or directory
setup-macos.sh: line 59: wget: command not found
unzip:  cannot find or open chrome-mac-arm64.zip, chrome-mac-arm64.zip.zip or chrome-mac-arm64.zip.ZIP.
mv: rename chrome-mac-arm64/ to /Users/collective/chrome-mac-arm64/: No such file or directory
mv: rename /Users/collective/chrome-mac-arm64/ to /Users/collective/chrome-testing/chrome-mac-arm64/: No such file or directory
rm: chrome-mac-arm64.zip: No such file or directory
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.

Cloning into 'LaVague'...
remote: Enumerating objects: 1446, done.
remote: Counting objects: 100% (717/717), done.
remote: Compressing objects: 100% (313/313), done.
remote: Total 1446 (delta 517), reused 508 (delta 393), pack-reused 729
Receiving objects: 100% (1446/1446), 25.50 MiB | 43.31 MiB/s, done.
Resolving deltas: 100% (781/781), done.
WARNING: The directory '/Users/collective/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Obtaining file:///Users/collective/Downloads/LaVague/LaVague
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting llama-index==0.10.19 (from lavague==1.0.5)
  Downloading llama_index-0.10.19-py3-none-any.whl.metadata (8.8 kB)
Collecting llama-index-agent-openai==0.1.5 (from lavague==1.0.5)
  Downloading llama_index_agent_openai-0.1.5-py3-none-any.whl.metadata (695 bytes)
Collecting llama-index-cli==0.1.9 (from lavague==1.0.5)
  Downloading llama_index_cli-0.1.9-py3-none-any.whl.metadata (1.5 kB)
Collecting llama-index-core==0.10.19 (from lavague==1.0.5)
  Downloading llama_index_core-0.10.19-py3-none-any.whl.metadata (3.6 kB)
Collecting llama-index-embeddings-azure-openai==0.1.5 (from lavague==1.0.5)
  Downloading llama_index_embeddings_azure_openai-0.1.5-py3-none-any.whl.metadata (796 bytes)
Collecting llama-index-embeddings-openai==0.1.6 (from lavague==1.0.5)
  Downloading llama_index_embeddings_openai-0.1.6-py3-none-any.whl.metadata (654 bytes)
Collecting llama-index-indices-managed-llama-cloud==0.1.4 (from lavague==1.0.5)
  Downloading llama_index_indices_managed_llama_cloud-0.1.4-py3-none-any.whl.metadata (3.8 kB)
Collecting llama-index-legacy==0.9.48 (from lavague==1.0.5)
  Downloading llama_index_legacy-0.9.48-py3-none-any.whl.metadata (8.5 kB)
Collecting llama-index-llms-azure-openai==0.1.5 (from lavague==1.0.5)
  Downloading llama_index_llms_azure_openai-0.1.5-py3-none-any.whl.metadata (786 bytes)
Collecting llama-index-llms-litellm==0.1.4 (from lavague==1.0.5)
  Downloading llama_index_llms_litellm-0.1.4-py3-none-any.whl.metadata (630 bytes)
Collecting llama-index-llms-openai==0.1.9 (from lavague==1.0.5)
  Downloading llama_index_llms_openai-0.1.9-py3-none-any.whl.metadata (558 bytes)
Collecting llama-index-multi-modal-llms-openai==0.1.4 (from lavague==1.0.5)
  Downloading llama_index_multi_modal_llms_openai-0.1.4-py3-none-any.whl.metadata (728 bytes)
Collecting llama-index-program-openai==0.1.4 (from lavague==1.0.5)
  Downloading llama_index_program_openai-0.1.4-py3-none-any.whl.metadata (766 bytes)
Collecting llama-index-question-gen-openai==0.1.3 (from lavague==1.0.5)
  Downloading llama_index_question_gen_openai-0.1.3-py3-none-any.whl.metadata (785 bytes)
Collecting llama-index-readers-file==0.1.9 (from lavague==1.0.5)
  Downloading llama_index_readers_file-0.1.9-py3-none-any.whl.metadata (969 bytes)
Collecting llama-index-readers-llama-parse==0.1.3 (from lavague==1.0.5)
  Downloading llama_index_readers_llama_parse-0.1.3-py3-none-any.whl.metadata (3.6 kB)
Collecting llama-index-retrievers-bm25==0.1.3 (from lavague==1.0.5)
  Downloading llama_index_retrievers_bm25-0.1.3-py3-none-any.whl.metadata (700 bytes)
INFO: pip is looking at multiple versions of lavague to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.8.1,<3.12; 0.0.2 Requires-Python >=3.8.1,<3.12; 0.0.2a0 Requires-Python >=3.8.1,<3.12; 0.0.3 Requires-Python >=3.8.1,<3.12; 0.0.4 Requires-Python >=3.8.1,<3.12; 0.0.5 Requires-Python >=3.8.1,<3.12; 0.0.6 Requires-Python >=3.8.1,<3.12; 0.0.7 Requires-Python >=3.8.1,<3.12; 0.0.8 Requires-Python >=3.8.1,<3.12; 0.1.0 Requires-Python >=3.8.1,<3.12; 0.1.1 Requires-Python >=3.8.1,<3.12; 0.1.2 Requires-Python >=3.8.1,<3.12; 0.1.2 Requires-Python >=3.9,<3.12; 0.1.3 Requires-Python >=3.8.1,<3.12; 0.1.4 Requires-Python >=3.8.1,<3.12; 0.10.0 Requires-Python >=3.8.1,<3.12; 0.10.1 Requires-Python >=3.8.1,<3.12; 0.10.11 Requires-Python >=3.8.1,<3.12; 0.10.12 Requires-Python >=3.8.1,<3.12; 0.10.3 Requires-Python >=3.8.1,<3.12; 0.10.4 Requires-Python >=3.8.1,<3.12; 0.21.0 Requires-Python <3.12,>=3.8; 0.8.43 Requires-Python >=3.8.1,<3.12; 0.8.43.post1 Requires-Python >=3.8.1,<3.12; 0.8.44 Requires-Python >=3.8.1,<3.12; 0.8.45 Requires-Python >=3.8.1,<3.12; 0.8.45.post1 Requires-Python >=3.8.1,<3.12; 0.8.46 Requires-Python >=3.8.1,<3.12; 0.8.47 Requires-Python >=3.8.1,<3.12; 0.8.48 Requires-Python >=3.8.1,<3.12; 0.8.49 Requires-Python >=3.8.1,<3.12; 0.8.50 Requires-Python >=3.8.1,<3.12; 0.8.51 Requires-Python >=3.8.1,<3.12; 0.8.51.post1 Requires-Python >=3.8.1,<3.12; 0.8.52 Requires-Python >=3.8.1,<3.12; 0.8.53 Requires-Python >=3.8.1,<3.12; 0.8.53.post3 Requires-Python >=3.8.1,<3.12; 0.8.54 Requires-Python >=3.8.1,<3.12; 0.8.55 Requires-Python >=3.8.1,<3.12; 0.8.56 Requires-Python >=3.8.1,<3.12; 0.8.57 Requires-Python >=3.8.1,<3.12; 0.8.58 Requires-Python >=3.8.1,<3.12; 0.8.59 Requires-Python >=3.8.1,<3.12; 0.8.61 Requires-Python >=3.8.1,<3.12; 0.8.62 Requires-Python >=3.8.1,<3.12; 0.8.63.post1 Requires-Python >=3.8.1,<3.12; 0.8.63.post2 Requires-Python >=3.8.1,<3.12; 0.8.64 Requires-Python >=3.8.1,<3.12; 0.8.64.post1 Requires-Python >=3.8.1,<3.12; 0.8.65 Requires-Python >=3.8.1,<3.12; 0.8.66 Requires-Python >=3.8.1,<3.12; 0.8.67 Requires-Python >=3.8.1,<3.12; 0.8.68 Requires-Python >=3.8.1,<3.12; 0.8.69 Requires-Python >=3.8.1,<3.12; 0.8.69.post1 Requires-Python >=3.8.1,<3.12; 0.8.69.post2 Requires-Python >=3.8.1,<3.12; 0.9.0 Requires-Python >=3.8.1,<3.12; 0.9.0.post1 Requires-Python >=3.8.1,<3.12; 0.9.0a1 Requires-Python >=3.8.1,<3.12; 0.9.0a2 Requires-Python >=3.8.1,<3.12; 0.9.0a3 Requires-Python >=3.8.1,<3.12; 0.9.1 Requires-Python >=3.8.1,<3.12; 0.9.10 Requires-Python >=3.8.1,<3.12; 0.9.10a1 Requires-Python >=3.8.1,<3.12; 0.9.10a2 Requires-Python >=3.8.1,<3.12; 0.9.11 Requires-Python >=3.8.1,<3.12; 0.9.11.post1 Requires-Python >=3.8.1,<3.12; 0.9.2 Requires-Python >=3.8.1,<3.12; 0.9.3 Requires-Python >=3.8.1,<3.12; 0.9.3.post1 Requires-Python >=3.8.1,<3.12; 0.9.4 Requires-Python >=3.8.1,<3.12; 0.9.5 Requires-Python >=3.8.1,<3.12; 0.9.6 Requires-Python >=3.8.1,<3.12; 0.9.6.post1 Requires-Python >=3.8.1,<3.12; 0.9.6.post2 Requires-Python >=3.8.1,<3.12; 0.9.7 Requires-Python >=3.8.1,<3.12; 0.9.8 Requires-Python >=3.8.1,<3.12; 0.9.8.post1 Requires-Python >=3.8.1,<3.12; 0.9.9 Requires-Python >=3.8.1,<3.12
ERROR: Could not find a version that satisfies the requirement tree-sitter==0.21.0 (from lavague) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21.1, 0.21.2, 0.21.3)
ERROR: No matching distribution found for tree-sitter==0.21.0
\e[32mAll steps completed successfully.\e[0m

**Closed** 2024-04-17 15:51 UTC
Labels: help wanted, community-assigned
