### ISSUE TITLE
LaVague unable to correctly target input elements

### ISSUE THREAD

**Issue by lyie28** [lavague-ai/LaVague#330] opened 2024-06-10 15:22 UTC
If you try using LaVague with Google when you are not signed in, LaVague can't handle the 'continue without singing in' pop-up and when you are signed in, LaVague is unable to locate/click on the search bar - could be interesting to debug why

**Comment by paulpalmieri** [comment] 2024-06-12 13:08
I can confirm that the search bar cannot be targeted. When you manually extract the XPath, it is //*[@id="APjFqb"].

I will check again tomorrow to see if this XPath changes. I suspect that Google might dynamically change the page structure to prevent bots.

**Comment by paulpalmieri** [comment] 2024-06-19 15:23
We originally looked at Google, but discovered that the issue is more widespread. LaVague struggles at targeting inputs (search bars) on many different websites (Bing, Google, Reddit, Apple, Nike, Puma)

The instruction we used is "Search for LaVague" but you can put anything with a purpose of targeting a search input. 

- On the Puma website, LaVague tries to target an hidden element ((#353)
- On the other ones, we're having a hard time pinpointing why LaVague fails

**Comment by adeprez** [comment] 2024-06-28 15:49
When we try a search on google, the retriever fails to locate the search bar. The given XPath matches no DOM element.

When the searchbar is being targeted, the XPath found is `/html/body/div[1]/div[3]/form/div[1]/div[1]/div[2]/div[4]/div[6]/center/input[1]` (no match) but it should be `/html/body/div/div[3]/form/div/div/div/div/div[2]/textarea` (matches)

XPath is valid until `/html/body/div[1]/div[3]/form/div[1]/div[1]/div[2]/div[4]/div[6]`, but then no `center` node can be found. Furthermore, the div[6] should be filtered out because it has a display:none style.

**Comment by adeprez** [comment] 2024-07-17 15:21
Closing as resolved

**Closed by adeprez** 2024-07-17 15:21 UTC
Labels: bug, AI-performance, HighPrio
